### ISSUE TITLE
Panoramatic pictures feature requests

### ISSUE THREAD

**Issue by T0biasCZe** [HerrZatacke/gb-printer-web#101] opened 2022-06-22 17:45 UTC
When you print panoramatic pictures, it prints them without any frame, with just white letterboxing on the sides. In the app, there could be an option to re-add the frame. The photos could also be auto-rotated
example:
![20220621-224230-4x-bw](https://user-images.githubusercontent.com/44525446/175102465-ba7e6858-739b-4ddd-8663-d63a1f71451d.png)
![20220621-224542-4x-bw](https://user-images.githubusercontent.com/44525446/175102499-17c42713-d585-4125-9acc-8256d452d6cc.png)
![20220621-224230-4x-bwe](https://user-images.githubusercontent.com/44525446/175102737-b202a9c5-698a-4fb8-827d-8aa3bc9b6323.png)
![20220621-224542-4x-bwe](https://user-images.githubusercontent.com/44525446/175102521-26b99b30-a31e-420c-a133-11868e68cdae.png)

Since each panorama size has different print out resolution, and there are only 6 possible sizes (3 vertical, 3 horizontal) it could just detect the resolution, and depending on that overlay it to correct frame

**Comment by HerrZatacke** [comment] 2023-01-08 09:02
Duplicate of #49

**Closed by HerrZatacke** 2023-01-08 09:02 UTC
